sudo: required
services:
  - docker
python:
  - 3.12.0
#  - 3.9
#  - 3.10
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_93975980c32f_key -iv $encrypted_93975980c32f_iv -in frontend-complex-k8s.json.enc -out frontend-complex-k8s.json -d
  
  - sudo apt-get -y install python
#  - curl https://sdk.cloud.google.com | bash > /dev/null;



  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc

  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project frontend-complex-k8s
  - gcloud config set compute/zone us-central1
  - gcloud container clusters get-credentials frontend-complex-k8s
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t panak4572/frontend-complex-k8s-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
